title: "Adonis The DemiGod's Website"
description: "The personal site for Adonis The DemiGod."
email: astericky@gmail.com
paginate: 10

safe: true
lsi: false
pygments: true
markdown: kramdown
permalink: pretty

